import requests
from gtts import gTTS
import os

def test_backend():
    # 1. Generate a test audio file using gTTS saying a valid game phrase
    phrase = "start the car"
    print(f"Generating audio for phrase: '{phrase}'...")
    
    tts = gTTS(text=phrase, lang='en')
    test_audio_path = "test_audio.mp3"
    tts.save(test_audio_path)
    print(f"Saved test audio to {test_audio_path}")
    
    # 2. Send it to the FastAPI backend
    url = "http://localhost:8000/api/transcribe"
    
    print(f"\nSending POST request to {url}...")
    
    with open(test_audio_path, "rb") as f:
        files = {"file": ("test_audio.mp3", f, "audio/mpeg")}
        data = {
            "stage": "WAITING_START",
            "expected_phrase": phrase
        }
        
        try:
            response = requests.post(url, files=files, data=data)
            print("\n--- Response from Backend ---")
            print(f"Status Code: {response.status_code}")
            
            if response.status_code == 200:
                result = response.json()
                print("\nJSON Response:")
                print(f"Matched: {result.get('matched')}")
                print(f"Transcript generated by Whisper API: '{result.get('transcript')}'")
                print(f"Confidence (Fuzzy Match Score): {result.get('confidence')}%")
            else:
                print(response.text)
                
        except Exception as e:
            print(f"Error connecting to backend: {e}")
            
    # Cleanup
    if os.path.exists(test_audio_path):
        os.remove(test_audio_path)
        print("\nCleaned up test_audio.mp3")

if __name__ == "__main__":
    test_backend()
